#' Select the columns needed for \code{penalty_detection()}
#' @param pbp (\emph{data.frame} required) Play-by-Play dataframe pulled from API via the `cfb_pbp_data()` function
#' @importFrom dplyr "select"
penalty_detection_select <- function(pbp) {
  
  pbp <- pbp %>%
    dplyr::select(
      "game_id",
      "half",
      "period",
      "clock.minutes",
      "clock.seconds",
      "down",
      "distance",
      "yards_to_goal",
      "orig_play_type",
      "play_type",
      "play_text",
      "penalty_flag",
      "penalty_declined",
      "penalty_no_play",
      "penalty_offset",
      "penalty_1st_conv",
      "penalty_text",
      everything()
    )
  return(pbp)
  
}



#' Select the columns needed for \code{add_play_counts()}
#' @param pbp (\emph{data.frame} required) Play-by-Play dataframe pulled from API via the `cfb_pbp_data()` function
#' @importFrom dplyr "select"
add_play_counts_select <- function(pbp) {
  
  pbp <- pbp %>%
    dplyr::select(
      "game_id",
      "id_play",
      "game_play_number",
      "half_play_number",
      "offense_play",
      "defense_play",
      "play",
      "half_play",
      "half",
      "period",
      "clock.minutes",
      "clock.seconds",
      "TimeSecsRem",
      "Under_two",
      "Under_three",
      "down",
      "distance",
      "yards_to_goal",
      "yards_gained",
      "play_type",
      "play_text",
      "kickoff_play",
      "receives_2H_kickoff",
      "offense_receives_2H_kickoff",
      "home",
      "away",
      "lag_offense_play",
      "lead_offense_play",
      "lead_offense_play",
      "score_diff",
      "lag_score_diff",
      "score_pts",
      "score_diff_start",
      "lag_off_timeouts",
      "lag_def_timeouts",
      "off_timeouts_rem_before",
      "def_timeouts_rem_before",
      "off_timeout_called",
      "def_timeout_called",
      "lead_play_type",
      "lead_play_type2",
      "lead_play_type3",
      "change_of_poss",
      everything()
    )
  return(pbp)
}


#' Select the columns needed for \code{clean_pbp_dat()}
#' @param pbp (\emph{data.frame} required) Play-by-Play dataframe pulled from API via the `cfb_pbp_data()` function
#' @importFrom dplyr "select"
clean_pbp_dat_select <- function(pbp) {
  
  pbp <- pbp %>%
    dplyr::select(
      "game_id",
      "id_play",
      "home",
      "away",
      "offense_play",
      "defense_play",
      "orig_play_type",
      "play_type",
      "play_text",
      "yards_to_goal",
      "down",
      "distance",
      "yards_gained",
      "penalty_1st_conv",      
      "pos_team",
      "lead_pos_team",
      "lead_pos_team2",
      "change_of_pos_team",
      "change_of_poss",
      "def_pos_team",
      "fumble_vec",
      "downs_turnover",
      "turnover_vec",
      "scoring_play",
      "td_play",
      "touchdown",
      "off_td_play",
      "def_td_play",
      "td_check",
      "off_timeouts_rem_before",
      "def_timeouts_rem_before",
      "pos_team_timeouts_rem",
      "def_pos_team_timeouts_rem",
      "rush_vec",
      "rush_td",
      "pass_vec",
      "completion",
      "pass_attempt",
      "target",
      "pass_td",
      "int",
      "int_td",
      "sack_vec",
      "sack",
      "safety",
      "fg_inds",
      "yds_fg",
      "kickoff_play",
      "kickoff_tb",
      "kickoff_onside",
      "kickoff_oob",
      "kickoff_fair_catch",
      "kickoff_downed",
      "kick_play",
      "kickoff_safety",
      "punt",
      "punt_play",
      "punt_tb",
      "punt_oob",
      "punt_fair_catch",
      "punt_downed",
      everything()
    )
  return(pbp)
}


#' Select the columns needed for \code{clean_drive_dat()}
#' @param pbp (\emph{data.frame} required) Play-by-Play dataframe pulled from API via the `cfb_pbp_data()` function
#' @importFrom dplyr "select"
clean_drive_dat_select <- function(pbp) {
  
  pbp <- pbp %>%
    dplyr::select(
      "game_id",
      "id_play",
      "home",
      "away",
      "offense_play",
      "defense_play",
      "orig_play_type",
      "play_type",
      "play_text",
      "yards_to_goal",
      "down",
      "distance",
      "yards_gained",
      "penalty_1st_conv",      
      "pos_team",
      "lead_pos_team",
      "lead_pos_team2",
      "change_of_pos_team",
      "change_of_poss",
      "def_pos_team",      
      "log_ydstogo",
      "Goal_To_Go",
      "drive_numbers",
      "number_of_drives",
      "pts_scored",
      "new_drive_result",
      "new_drive_pts",
      "drive_scoring",
      "new_drive_result2",
      "drive_play",
      "drive_play_number",
      "lag_change_of_poss",
      "lag_punt",
      "lag_scoring_play",
      "lag_turnover_vec",
      "lag_downs_turnover",
      "fumble_vec",
      "downs_turnover",
      "turnover_vec",
      "scoring_play",
      "td_play",
      "touchdown",
      "off_td_play",
      "def_td_play",
      "off_timeouts_rem_before",
      "def_timeouts_rem_before",
      "pos_team_timeouts_rem",
      "def_pos_team_timeouts_rem",
      "lead_play_type",
      "lead_play_type2",
      "lead_play_type3",
      "rush_vec",
      "rush_td",
      "pass_vec",
      "completion",
      "pass_attempt",
      "target",
      "pass_td",
      "int",
      "int_td",
      "sack_vec",
      "sack",
      "safety",
      "fg_inds",
      "yds_fg",
      "kickoff_play",
      "kickoff_tb",
      "kickoff_onside",
      "kickoff_oob",
      "kickoff_fair_catch",
      "kickoff_downed",
      "kick_play",
      "kickoff_safety",
      "punt",
      "punt_play",
      "punt_tb",
      "punt_oob",
      "punt_fair_catch",
      "punt_downed",
      "new_id",
      everything()
      
    )
  return(pbp)
}


#' Select the columns needed for \code{prep_epa_df_after()}
#' @param pbp (\emph{data.frame} required) Play-by-Play dataframe pulled from API via the `cfb_pbp_data()` function
#' @importFrom dplyr "select"
prep_epa_df_after_select <- function(pbp) {
  
  pbp <- pbp %>%
    dplyr::select(
      "game_id",
      "id_play",
      "home",
      "away",
      "game_play_number",
      "half_play_number",      
      "drive_play_number",
      "offense_play",
      "defense_play",
      "half",
      "period",
      "clock.minutes",
      "clock.seconds",
      "orig_play_type",
      "play_type",
      "play_text",
      "yards_to_goal",
      "new_yardline",
      "down",
      "distance",
      "new_distance",
      "yards_gained",
      "penalty_1st_conv",      
      "pos_team",
      "lead_pos_team",
      "lead_pos_team2",
      "change_of_pos_team",
      "change_of_poss",
      "def_pos_team",      
      "end_of_half",
      "TimeSecsRem",
      "new_TimeSecsRem",
      "Under_two",
      "Under_three",
      "new_Under_two",
      "new_log_ydstogo",      
      "log_ydstogo",
      "Goal_To_Go",
      "new_Goal_To_Go",
      "turnover_indicator",
      "down",
      "new_id",
      "new_down",
      "distance",
      "yards_to_goal",
      "yards_gained",
      "turnover",
      "drive_start_yards_to_goal",
      "first_by_penalty",
      "first_by_yards",
      "firstD_by_poss",
      "firstD_by_yards",
      "firstD_by_penalty",
      "yds_punted",
      "yds_punt_gained",
      "missing_yard_flag",
      "drive_numbers",
      "number_of_drives",
      "pts_scored",
      "new_drive_result",
      "new_drive_pts",
      "drive_scoring",
      "new_drive_result2",
      "lag_change_of_poss",
      "lag_punt",
      "lag_scoring_play",
      "lag_turnover_vec",
      "lag_downs_turnover",
      "fumble_vec",
      "downs_turnover",
      "turnover_vec",
      "scoring_play",
      "touchdown",
      "off_td_play",
      "def_td_play",
      "off_timeouts_rem_before",
      "def_timeouts_rem_before",
      "pos_team_timeouts_rem",
      "def_pos_team_timeouts_rem",
      "lead_play_type",
      "lead_play_type2",
      "lead_play_type3",
      "rush_vec",
      "rush_td",
      "pass_vec",
      "completion",
      "pass_attempt",
      "target",
      "pass_td",
      "int",
      "int_td",
      "sack_vec",
      "sack",
      "safety",
      "fg_inds",
      "yds_fg",
      "kickoff_play",
      "kickoff_tb",
      "kickoff_onside",
      "kickoff_oob",
      "kickoff_fair_catch",
      "kickoff_downed",
      "kick_play",
      "kickoff_safety",
      "punt",
      "punt_play",
      "punt_tb",
      "punt_oob",
      "punt_fair_catch",
      "punt_downed",
      "new_id",
      everything()
    )
  return(pbp)
}
